#!/usr/bin/python
print("HOla Mundo")
import readline
readline.write_history_file("Hola.py")
exit()
#!/usr/bin/python
print("Hola mundo")
exit()
#!/usr/bin/python
print("Hola mundo")
import readline
readline.write_history_file("hy.py")
exit()
#!/usr/bin/python
print("hola mundo")
import readline
readline.write_history_file("0-run")
